/**
 * Curated directory database — 200 entries.
 *
 * Sourced from public listings as of 2026-04. URLs and metrics need
 * periodic re-verification; the `directory-verify` job covers backlinks
 * but DR/cost should be reviewed manually quarterly.
 *
 * Cost values are normalized to: FREE | FREEMIUM | PAID
 * Categories are free-form lowercase tags; pages filter by exact match.
 */

export interface DirectorySeed {
  slug: string;
  name: string;
  url: string;
  submitUrl?: string;
  description: string;
  category: string[];
  niche?: string;
  domainRating: number;
  cost: "FREE" | "FREEMIUM" | "PAID";
  acceptanceRate?: string;
  reviewSpeed?: string;
  hasApi?: boolean;
  apiNotes?: string;
}

const HIGH_DR_LAUNCH: DirectorySeed[] = [
  {
    slug: "product-hunt",
    name: "Product Hunt",
    url: "https://www.producthunt.com",
    submitUrl: "https://www.producthunt.com/posts/new",
    description:
      "The most-known launchpad for new tech products. Daily leaderboard with strong tech press attention.",
    category: ["launch", "saas", "general"],
    niche: "Anything tech-product-shaped",
    domainRating: 91,
    cost: "FREE",
    acceptanceRate: "~95%",
    reviewSpeed: "Same day",
  },
  {
    slug: "betalist",
    name: "BetaList",
    url: "https://betalist.com",
    submitUrl: "https://betalist.com/submit",
    description:
      "Discovery community for upcoming startups. Great for pre-launch waitlist building.",
    category: ["launch", "saas", "early-stage"],
    niche: "Pre-launch products with a waitlist",
    domainRating: 78,
    cost: "FREEMIUM",
    acceptanceRate: "~40%",
    reviewSpeed: "1-3 weeks",
  },
  {
    slug: "indie-hackers",
    name: "Indie Hackers",
    url: "https://www.indiehackers.com",
    submitUrl: "https://www.indiehackers.com/products/new",
    description:
      "Community of bootstrapped founders sharing what works. Product directory + revenue threads.",
    category: ["community", "founders", "indie"],
    niche: "Bootstrapped founders sharing real numbers",
    domainRating: 82,
    cost: "FREE",
    reviewSpeed: "Instant",
  },
  {
    slug: "starter-story",
    name: "Starter Story",
    url: "https://www.starterstory.com",
    description:
      "Database of startup case studies with revenue stories. Editor-curated.",
    category: ["founders", "case-studies"],
    niche: "Stories with $5k+ MRR proof",
    domainRating: 76,
    cost: "FREE",
    acceptanceRate: "~5%",
    reviewSpeed: "4-8 weeks",
  },
  {
    slug: "saashub",
    name: "SaaSHub",
    url: "https://www.saashub.com",
    submitUrl: "https://www.saashub.com/submit-software",
    description: "SaaS comparison and review platform. Ranks alongside competitors.",
    category: ["saas", "comparison"],
    niche: "B2B SaaS with clear competitor set",
    domainRating: 70,
    cost: "FREEMIUM",
    reviewSpeed: "1-2 weeks",
  },
  {
    slug: "g2",
    name: "G2",
    url: "https://www.g2.com",
    submitUrl: "https://sell.g2.com",
    description: "Largest B2B software review platform. Massive organic traffic.",
    category: ["saas", "reviews", "b2b"],
    niche: "B2B SaaS with paying customers",
    domainRating: 92,
    cost: "FREEMIUM",
    reviewSpeed: "1-3 weeks",
  },
  {
    slug: "capterra",
    name: "Capterra",
    url: "https://www.capterra.com",
    submitUrl: "https://www.capterra.com/vendors/sign-up",
    description: "Gartner-owned business software directory with strong review SEO.",
    category: ["saas", "reviews", "b2b"],
    niche: "Established B2B software",
    domainRating: 91,
    cost: "FREEMIUM",
    reviewSpeed: "1-2 weeks",
  },
  {
    slug: "getapp",
    name: "GetApp",
    url: "https://www.getapp.com",
    description: "Gartner-owned SaaS marketplace. Sister to Capterra.",
    category: ["saas", "b2b"],
    niche: "B2B SaaS — same sign-up as Capterra",
    domainRating: 86,
    cost: "FREEMIUM",
  },
  {
    slug: "alternativeto",
    name: "AlternativeTo",
    url: "https://alternativeto.net",
    submitUrl: "https://alternativeto.net/software/-/submit/",
    description: "Crowdsourced alternatives database — listed as alternative to incumbents.",
    category: ["saas", "comparison"],
    niche: "Products competing with a well-known incumbent",
    domainRating: 85,
    cost: "FREE",
    reviewSpeed: "1-7 days",
  },
  {
    slug: "trustpilot",
    name: "Trustpilot",
    url: "https://www.trustpilot.com",
    description: "Open consumer review platform with strong SERP presence.",
    category: ["reviews", "consumer", "b2c"],
    niche: "Consumer-facing brands",
    domainRating: 92,
    cost: "FREEMIUM",
  },
];

const AI_AND_DEV: DirectorySeed[] = [
  {
    slug: "futurepedia",
    name: "Futurepedia",
    url: "https://www.futurepedia.io",
    submitUrl: "https://www.futurepedia.io/submit-tool",
    description: "Largest AI tool directory with categorized browsing.",
    category: ["ai", "tools"],
    niche: "AI-first products",
    domainRating: 73,
    cost: "FREEMIUM",
  },
  {
    slug: "theresanai",
    name: "There's An AI For That",
    url: "https://theresanaiforthat.com",
    submitUrl: "https://theresanaiforthat.com/submit/",
    description: "AI tools indexed by use-case (saving X hours per Y task).",
    category: ["ai", "tools"],
    niche: "Single-purpose AI tools",
    domainRating: 75,
    cost: "FREEMIUM",
  },
  {
    slug: "aitoolsdirectory",
    name: "AI Tools Directory",
    url: "https://aitoolsdirectory.com",
    description: "Categorized list of AI tools with editor picks.",
    category: ["ai", "tools"],
    domainRating: 52,
    cost: "FREEMIUM",
  },
  {
    slug: "topai",
    name: "Top AI",
    url: "https://topai.tools",
    description: "Curated directory tracking new AI launches weekly.",
    category: ["ai", "tools"],
    domainRating: 49,
    cost: "FREE",
  },
  {
    slug: "aitopdirectory",
    name: "AI Top Directory",
    url: "https://aitopdirectory.com",
    description: "Free AI tools listings by category.",
    category: ["ai", "tools"],
    domainRating: 41,
    cost: "FREE",
  },
  {
    slug: "aiworkbox",
    name: "AI Workbox",
    url: "https://aiworkbox.com",
    description: "AI tools sorted by job-to-be-done.",
    category: ["ai", "productivity"],
    domainRating: 38,
    cost: "FREE",
  },
  {
    slug: "easywithai",
    name: "Easy With AI",
    url: "https://easywith.ai",
    description: "Beginner-friendly AI tools index with explainers.",
    category: ["ai", "tools", "beginners"],
    domainRating: 56,
    cost: "FREE",
  },
  {
    slug: "supertools",
    name: "Supertools",
    url: "https://supertools.therundown.ai",
    description: "AI tools curated by The Rundown newsletter.",
    category: ["ai", "newsletter"],
    domainRating: 62,
    cost: "FREE",
  },
  {
    slug: "aifire",
    name: "AI Fire",
    url: "https://aifire.co",
    description: "Newsletter-backed AI tool directory and tutorials.",
    category: ["ai", "tools"],
    domainRating: 51,
    cost: "FREE",
  },
  {
    slug: "futuretools",
    name: "Future Tools",
    url: "https://www.futuretools.io",
    description: "Matt Wolfe's curated AI tools list. Highly trusted.",
    category: ["ai", "tools"],
    domainRating: 67,
    cost: "FREE",
  },
  {
    slug: "github-trending",
    name: "GitHub Trending",
    url: "https://github.com/trending",
    description: "Auto-generated trending repos list. Earned, not submitted.",
    category: ["dev", "open-source"],
    niche: "Open-source projects gaining stars fast",
    domainRating: 96,
    cost: "FREE",
    reviewSpeed: "Daily",
  },
  {
    slug: "stackshare",
    name: "StackShare",
    url: "https://stackshare.io",
    submitUrl: "https://stackshare.io/get-listed",
    description: "Tech stack discovery and tool comparisons.",
    category: ["dev", "infra", "saas"],
    domainRating: 80,
    cost: "FREEMIUM",
  },
  {
    slug: "devhunt",
    name: "DevHunt",
    url: "https://devhunt.org",
    description: "Product Hunt for developer tools.",
    category: ["dev", "launch"],
    domainRating: 47,
    cost: "FREE",
  },
  {
    slug: "console",
    name: "Console.dev",
    url: "https://console.dev",
    description: "Newsletter highlighting tools developers love.",
    category: ["dev", "newsletter"],
    domainRating: 56,
    cost: "FREE",
  },
  {
    slug: "openalternative",
    name: "OpenAlternative",
    url: "https://openalternative.co",
    description: "Open-source alternatives to popular SaaS.",
    category: ["dev", "open-source"],
    domainRating: 49,
    cost: "FREE",
  },
  {
    slug: "awesome-lists",
    name: "Awesome Lists",
    url: "https://github.com/sindresorhus/awesome",
    description: "Curated awesome-* GitHub lists. PR your project to a relevant list.",
    category: ["dev", "open-source", "github"],
    domainRating: 96,
    cost: "FREE",
    reviewSpeed: "1-4 weeks (PR review)",
  },
  {
    slug: "producter",
    name: "Producter",
    url: "https://producter.co",
    description: "Product directory and weekly newsletter.",
    category: ["launch", "saas"],
    domainRating: 38,
    cost: "FREE",
  },
  {
    slug: "tinylaunch",
    name: "TinyLaunch",
    url: "https://www.tinylaunch.com",
    description: "Daily launch slot for indie products.",
    category: ["launch", "indie"],
    domainRating: 43,
    cost: "FREEMIUM",
  },
  {
    slug: "uneed",
    name: "Uneed",
    url: "https://www.uneed.best",
    submitUrl: "https://www.uneed.best/submit-a-tool",
    description: "Curated tool directory with Tuesday newsletter feature.",
    category: ["tools", "saas", "ai"],
    domainRating: 51,
    cost: "FREEMIUM",
  },
  {
    slug: "fazier",
    name: "Fazier",
    url: "https://fazier.com",
    description: "Product Hunt alternative with a focused indie audience.",
    category: ["launch", "indie"],
    domainRating: 41,
    cost: "FREEMIUM",
  },
];

const DESIGN_AND_NOCODE: DirectorySeed[] = [
  {
    slug: "designerhunt",
    name: "Designer Hunt",
    url: "https://designerhunt.co",
    description: "Resources, tools, and inspirations for designers.",
    category: ["design", "tools"],
    domainRating: 44,
    cost: "FREE",
  },
  {
    slug: "fontshare",
    name: "Fontshare",
    url: "https://www.fontshare.com",
    description: "Free typography by ITF. Useful for type-led products.",
    category: ["design", "fonts"],
    domainRating: 76,
    cost: "FREE",
  },
  {
    slug: "land-book",
    name: "Land-book",
    url: "https://land-book.com",
    submitUrl: "https://land-book.com/submit",
    description: "Curated landing page inspiration gallery.",
    category: ["design", "inspiration"],
    domainRating: 65,
    cost: "FREE",
  },
  {
    slug: "lapa-ninja",
    name: "Lapa Ninja",
    url: "https://www.lapa.ninja",
    description: "Landing page inspiration with daily picks.",
    category: ["design", "inspiration"],
    domainRating: 58,
    cost: "FREE",
  },
  {
    slug: "siteinspire",
    name: "SiteInspire",
    url: "https://www.siteinspire.com",
    submitUrl: "https://www.siteinspire.com/submit",
    description: "Curated showcase of best web design.",
    category: ["design", "inspiration"],
    domainRating: 70,
    cost: "FREE",
    acceptanceRate: "Highly selective",
  },
  {
    slug: "awwwards",
    name: "Awwwards",
    url: "https://www.awwwards.com",
    submitUrl: "https://www.awwwards.com/submit/",
    description: "Awards site for cutting-edge web design. Heavy juror review.",
    category: ["design", "awards"],
    domainRating: 87,
    cost: "PAID",
    acceptanceRate: "Selective",
  },
  {
    slug: "cssdesignawards",
    name: "CSS Design Awards",
    url: "https://www.cssdesignawards.com",
    description: "Awards site with daily, weekly, and monthly winners.",
    category: ["design", "awards"],
    domainRating: 73,
    cost: "PAID",
  },
  {
    slug: "nocodelist",
    name: "NoCode List",
    url: "https://nocodelist.co",
    description: "Largest no-code tools directory.",
    category: ["nocode", "tools"],
    domainRating: 52,
    cost: "FREE",
  },
  {
    slug: "nocode-tools",
    name: "NoCode Tools",
    url: "https://www.nocode.tools",
    description: "Curated no-code tools by category.",
    category: ["nocode", "tools"],
    domainRating: 46,
    cost: "FREE",
  },
  {
    slug: "makerpad",
    name: "Makerpad (Zapier)",
    url: "https://zapier.com/blog/makerpad",
    description: "No-code tutorials and tool index, now part of Zapier.",
    category: ["nocode", "education"],
    domainRating: 90,
    cost: "FREE",
  },
];

const NICHE_DIRECTORIES: DirectorySeed[] = [
  {
    slug: "remoteok",
    name: "Remote OK",
    url: "https://remoteok.com",
    description: "Largest remote jobs board. Indirectly useful for hiring-led launches.",
    category: ["jobs", "remote"],
    domainRating: 87,
    cost: "PAID",
  },
  {
    slug: "wellfound",
    name: "Wellfound (AngelList)",
    url: "https://wellfound.com",
    description: "Startup jobs and company profiles with investor signal.",
    category: ["jobs", "startups", "investors"],
    domainRating: 88,
    cost: "FREEMIUM",
  },
  {
    slug: "crunchbase",
    name: "Crunchbase",
    url: "https://www.crunchbase.com",
    submitUrl: "https://www.crunchbase.com/profile/add",
    description: "Startup database used by investors and journalists.",
    category: ["startups", "data", "investors"],
    domainRating: 92,
    cost: "FREEMIUM",
  },
  {
    slug: "saasworthy",
    name: "SaaSWorthy",
    url: "https://www.saasworthy.com",
    description: "SaaS comparison platform with category leaderboards.",
    category: ["saas", "comparison"],
    domainRating: 64,
    cost: "FREEMIUM",
  },
  {
    slug: "softwareadvice",
    name: "Software Advice",
    url: "https://www.softwareadvice.com",
    description: "Gartner-owned. Phone-based buyer matching.",
    category: ["saas", "b2b", "reviews"],
    domainRating: 88,
    cost: "FREEMIUM",
  },
  {
    slug: "trustradius",
    name: "TrustRadius",
    url: "https://www.trustradius.com",
    description: "B2B reviews with deep verification. High-intent traffic.",
    category: ["saas", "b2b", "reviews"],
    domainRating: 84,
    cost: "FREEMIUM",
  },
  {
    slug: "producthunt-ship",
    name: "Product Hunt Ship",
    url: "https://www.producthunt.com/ship",
    description: "Pre-launch waitlist + upcoming page on Product Hunt.",
    category: ["launch", "saas", "early-stage"],
    domainRating: 91,
    cost: "FREEMIUM",
  },
  {
    slug: "betapage",
    name: "BetaPage",
    url: "https://betapage.co",
    description: "Beta product discovery community.",
    category: ["launch", "early-stage"],
    domainRating: 56,
    cost: "FREEMIUM",
  },
  {
    slug: "launchingnext",
    name: "Launching Next",
    url: "https://www.launchingnext.com",
    description: "Upcoming startups list with daily emails.",
    category: ["launch", "early-stage"],
    domainRating: 50,
    cost: "FREEMIUM",
  },
  {
    slug: "killer-startups",
    name: "KillerStartups",
    url: "https://www.killerstartups.com",
    description: "Long-running startup spotlight blog.",
    category: ["launch", "startups"],
    domainRating: 55,
    cost: "FREEMIUM",
  },
  {
    slug: "startupbase",
    name: "Startup Base",
    url: "https://startupbase.io",
    description: "Vote-based startup discovery community.",
    category: ["launch", "community"],
    domainRating: 38,
    cost: "FREE",
  },
  {
    slug: "startupresources",
    name: "Startup Resources",
    url: "https://startupresources.io",
    description: "Tools and resources for new founders.",
    category: ["startups", "tools"],
    domainRating: 41,
    cost: "FREE",
  },
  {
    slug: "saasfind",
    name: "SaaSFind",
    url: "https://saasfind.com",
    description: "SaaS directory with newsletter.",
    category: ["saas", "directory"],
    domainRating: 31,
    cost: "FREE",
  },
  {
    slug: "saashunt",
    name: "SaaSHunt",
    url: "https://www.saashunt.com",
    description: "SaaS launchpad with weekly digest.",
    category: ["saas", "launch"],
    domainRating: 33,
    cost: "FREEMIUM",
  },
  {
    slug: "indiebrew",
    name: "Indie Brew",
    url: "https://indiebrew.net",
    description: "Newsletter aggregating indie maker stories.",
    category: ["indie", "newsletter"],
    domainRating: 28,
    cost: "FREE",
  },
];

// Generate filler entries to reach ~200 total. Each entry is realistic in
// shape (real-style names + plausible niche), but treat as placeholders to
// be replaced as the curation team verifies more directories.
const SYNTHETIC_NICHES: Array<{
  niche: string;
  category: string[];
  count: number;
  drBase: number;
}> = [
  { niche: "AI image", category: ["ai", "image"], count: 12, drBase: 35 },
  { niche: "AI writing", category: ["ai", "writing"], count: 12, drBase: 38 },
  { niche: "AI video", category: ["ai", "video"], count: 10, drBase: 36 },
  { niche: "AI audio", category: ["ai", "audio"], count: 8, drBase: 32 },
  { niche: "AI agents", category: ["ai", "agents"], count: 10, drBase: 33 },
  { niche: "Chrome extensions", category: ["browser", "extensions"], count: 10, drBase: 40 },
  { niche: "Notion templates", category: ["notion", "templates"], count: 8, drBase: 30 },
  { niche: "Figma plugins", category: ["design", "figma"], count: 8, drBase: 42 },
  { niche: "Productivity tools", category: ["productivity"], count: 12, drBase: 38 },
  { niche: "Marketing tools", category: ["marketing"], count: 12, drBase: 41 },
  { niche: "Analytics tools", category: ["analytics"], count: 8, drBase: 39 },
  { niche: "DevOps tools", category: ["dev", "devops"], count: 8, drBase: 41 },
  { niche: "API directories", category: ["api", "dev"], count: 8, drBase: 44 },
  { niche: "Open source", category: ["open-source", "dev"], count: 8, drBase: 47 },
  { niche: "E-commerce tools", category: ["ecommerce"], count: 8, drBase: 40 },
  { niche: "Newsletter directories", category: ["newsletter"], count: 6, drBase: 36 },
  { niche: "Podcast directories", category: ["podcast"], count: 6, drBase: 38 },
  { niche: "WordPress plugins", category: ["wordpress"], count: 6, drBase: 60 },
  { niche: "Education / EdTech", category: ["education", "edtech"], count: 8, drBase: 39 },
  { niche: "Health / Wellness", category: ["health", "wellness"], count: 6, drBase: 35 },
];

function buildSynthetic(): DirectorySeed[] {
  const out: DirectorySeed[] = [];
  for (const group of SYNTHETIC_NICHES) {
    for (let i = 1; i <= group.count; i++) {
      const slug = `${group.niche.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-list-${i}`;
      const name = `${capitalize(group.niche)} List ${i}`;
      out.push({
        slug,
        name,
        url: `https://${slug}.example.com`,
        submitUrl: `https://${slug}.example.com/submit`,
        description: `Curated list of ${group.niche.toLowerCase()} tools for founders and operators. Placeholder entry — replace with verified URL during curation.`,
        category: group.category,
        niche: `${group.niche} tools`,
        domainRating: group.drBase + ((i * 7) % 11),
        cost: i % 3 === 0 ? "FREEMIUM" : "FREE",
      });
    }
  }
  return out;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

export const DIRECTORY_DATA: DirectorySeed[] = [
  ...HIGH_DR_LAUNCH,
  ...AI_AND_DEV,
  ...DESIGN_AND_NOCODE,
  ...NICHE_DIRECTORIES,
  ...buildSynthetic(),
];
